package com.partyum.partyummanager.base

enum class Command {
    // 메인
    NEW_RESERVATION,
    NEW_RESERVATION_SUBMITTED,
    SEARCH_RESERVATION,
    NUMBER_SUBMITTED,
    RESERVATION_STATUS,
    ADMINISTRATOR,

    // 예약
    MODIFY_RESERVATION,
    ADD_NEW_DOCUMENT,
    DELETE_RESERVATION,

    // 문서
    SHOW_MENU,
    VIEW_HISTORY,
    MODIFY_DOCUMENT,
    SAVE_TO_DATABASE,
    EXPORT,
    DELETE_DOCUMENT,
    MODIFIED_DOCUMENT_SUBMITTED,
    CLOSE_FRAGMENT,
}